openapi: "3.0.0"
info:
  title: Issue Tracker API
  version: 0.2.0
paths:
  /tickets:
    get:
      summary: Get all tickets
      operationId: getAll
      tags:
        - tickets
      responses:
        '200':
          description: A list of TicketDto objects
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: './dto/TicketDto.yaml'
    post:
      summary: Create a new ticket
      operationId: createTicket
      tags:
        - tickets
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: './dto/TicketPostDto.yaml'
      responses:
        201:
          description: Ticket created successfully
          content:
            application/json:
              schema:
                $ref: './dto/TicketPostResponseDto.yaml'